apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: cp-access
  namespace: confluent
spec:
  kafkaClusterRef:
    name: kafka
    namespace: confluent
  kafkaRest:
    endpoint: https://192.168.33.10:8090
    authentication:
      type: bearer
      bearer:
        secretRef: cp-credential
    tls:
      secretRef: cp-tls
