Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04-arm64"
  config.vm.box_check_update = false
  config.vm.hostname = "confluent"
  config.vm.disk :disk, primary: true, size: "100GB"
  
  config.vm.provider :vmware_desktop do |v|
      v.vmx["memsize"] = "8192"
  end

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    apt-get install -y git
    apt-get install -y net-tools
    apt-get install -y ldap-utils
    apt-get install -y jq

    # install docker
    apt-get install ca-certificates curl gnupg -y
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update
    apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

    # download docker-ldap 
    git clone https://github.com/ram-pi/docker-ldap.git
    cd docker-ldap
    # replace localhost with 192.168.33.10 in .env file
    sed -i 's/localhost/192.168.33.10/g' .env 
    docker compose up -d
  SHELL

end
